### ISSUE TITLE
Video convert option does not show up.

### ISSUE THREAD

**Issue by SamWang8891TW** [zelon88/HRConvert2#16]
Disclaim: If this post shouldn't been posted here, please inform me and I will remove it. Thanks!

When upload video, the web shows up : "You have uploaded 0 valid files to HRConvert2."
<img width="1062" alt="Screen Shot 2022-04-24 at 4 24 24 PM" src="https://user-images.githubusercontent.com/73735177/164967358-350d275a-4908-491c-bf0f-618559dfb896.png">
<img width="1021" alt="Screen Shot 2022-04-24 at 4 20 47 PM" src="https://user-images.githubusercontent.com/73735177/164967184-9f102378-f868-4da8-8729-092b13cedf32.png">
I've tried mp4 and mkv video formats and they don't work. But other format works fine(eg. pdf, stl, mp3, jpg....).
Also, I built this server on a virtual machine on ubuntu headless server (without GUI). I've done everything according to the guide "How_To_Install_HRConvert2.txt". 

Could vm possibly to be an issue, or because I didn't install a GUI?

Thanks for replying!

**Comment by zelon88** [comment]
Hmmmm, interesting. I have tried reproducing these results but conversions work for me. HRConvert2 identifies the file type by the extension of the file, not MIME file type. Can you rename your file to `video.mp4.txt` HRConvert2 would (incorrectly) identify it as a txt file. So I don't think that not having a window manager on your server is a big deal. What _might_ be a big deal later is whether or not you selected to install the 3rd party packages when prompted during OS installation. I've never tried running HRConvert2 without that package installed and I suspect that a lot of things might break. But the problem displayed here is not one of them. 

I suspect your version is v2.7. The instruction file name you provided was renamed to "INSTALLATION_INSTRUCTIONS.txt" in v2.8.2, but the wording on the landing page is at least v2.7. So your version must be between those two.

The video I used to test was "Equine Trot (Left) @ 400fps 1330 x 402 (~392MB)" from https://www.quinticsports.com/sample-videos/. I converted this video into MP4 (successfully), then downloaded that MP4 and reuploaded it before converting it again (successfully) into MKV and 3GP by redownloading and reuploading (to force the new files through the upload process as the new file type).

Please check the version in `versionInfo.php` and let me know what that is. Then please try the conversion using the video listed above. I suspect this video will also not show up. Also can you try renaming your original file to `filename.mp4.txt' and tell me if it appears in the list of uploaded files? Also if you could redact and submit the last few lines of your logfile from the `Logs` directory it would be helpful. 

If all else fails or is too much you can try getting the latest version from https://github.com/zelon88/HRConvert2/archive/refs/heads/master.zip and running the dependency installation section one more time just to be sure you have everything. Then adjust config.php and you try again. Updating HRConvert2 manually after installation is just a matter of backing up your existing config.php, overwriting the file, and then re-entering the config.php info into the new config file (incase any new features were added).

**Comment by SamWang8891TW** [comment]
First, thanks for the reply.

I confirmed that the version is v2.7 (not docker), which is the current release version. (4/15/2022)

Second, guess what? I broke my nextcloud and Wordpress and lighttpd which I use to manage pihole. So I have to fix the enormous issues first. LOL

After I fix them, I will test the converter using your method(change the file extension name) and reply this issue. Thanks for your patience.

**Comment by SamWang8891TW** [comment]
Unfortunately, it does not. Cheating on the file name does not make it accept. 

Real txt-> accepted
Fake txt(filename modified from a video file(mov)) -> not accepted 
Fake txt(6mb) -> not accepted
other format -> accepted

**Comment by chillyka88** [comment]
is there a solution would like to use it

**Comment by zelon88** [comment]
I'll look into this again and report back. Can you post the relevant HRConvert2 log file (located in the "Logs" subdirectory)? You may omit any sensitive information.

**Comment by gingerbread233** [comment]
Unfortunately I have the same issue. Some JPG's/files get recognized, some not, some even get recognized (1 Valid file), but its missing the options below, where I can choose what to do with the file. I dragged 14 .stl files, only 11 where "valid".

![leel1](https://user-images.githubusercontent.com/28112983/197355903-598ef79a-e625-48d7-988d-052674588709.JPG)
![leel2](https://user-images.githubusercontent.com/28112983/197355909-5a2cd8c0-ccfb-43d4-8e06-0bf050cd9a79.JPG)

**Comment by zelon88** [comment]
Sorry for the late reply. We recently updated the way whitespace in filenames is handled. I would try updating to v3.1 to see if the problem is resolved.

If not, could you do a "View Source" on a page that displays this behavior and post the source code?

Also, could you supply the relevant section of logfile that corresponds with this behaviour? You can redact filenames, but please note the presence of any special characters or whitespace in the file names you redact.
