### ISSUE TITLE
COPY AND PASTE THE INCLUDED "rc-local.service" FILE TO "/etc/systemd/system/rc-local.service"**

### ISSUE THREAD

**Issue by toxinliquid** [zelon88/HRConvert2#18]
where is this file ? cannot be found anywhere in the repo

**Comment by toxinliquid** [comment]
i have set the rc.local
but i cant find the rc-local.service
Thank you

**Comment by sbyland** [comment]
@toxinliquid  you need this. [](https://github.com/catinello/rc-local.service)

**Comment by zelon88** [comment]
Thanks @sbyland!

@toxinliquid, please try following the instructions at the following URL;
https://marsown.com/wordpress/how-to-enable-etc-rc-local-with-systemd-on-ubuntu-20-04/
