### ISSUE TITLE
Cannot install on a Synology NAS

### ISSUE THREAD

**Issue by fruizaviles** [zelon88/HRConvert2#21]
Using Docker I cannot install HRConvert2 since the software it uses to make conversions is not ready to be installed in containers. Is there any possibility to have this running in my NAS, being stand alone or Docker container? My computer skills are limited to do so, but have tried to find a solution without success. I believe we all dream with such a self hosted solution, so would be a nice improvement that may boost its current users. 
Cheers,

franeque

**Comment by zelon88** [comment]
Hello,

Can you send me a screenshot of the error you're getting?
