### ISSUE TITLE
Video to Gif conversion

### ISSUE THREAD

**Issue by maccers** [zelon88/HRConvert2#29]
Is it possible to add video to gif conversion in the future? Thank you!

**Comment by magnusv0s** [comment]
definitely would love this as well

**Comment by zelon88** [comment]
I think we could do that using ffmpeg.

**Comment by zelon88** [comment]
This is enabled in v3.3.7 with the latest ffmpeg build process.

To upgrade ffmpeg, run the ffmpeg-build.sh script under Documentation/Build/ffmpeg-build.sh. You may have to uninstall your existing ffmpeg first.
