### ISSUE TITLE
does not convert office files

### ISSUE THREAD

**Issue by changchichung** [zelon88/HRConvert2#3]
I build a HRConvert2 service with docker-compose downloaded from https://github.com/dwaaan/HRConvert2-Docker , but after uopload file and choose file format to convert , then I got nothing.
there is only one green animated icon keep going , but no any popup window to save as new file or anything else . 
I tried various types , txt/doc/odf/ods , none of these files can be converted. but mp4 convert to mkv is fine. maybe it's related to libreoffice ?

**Comment by changchichung** [comment]
and here is part of log
```
OP-Act, The document conversion engine PID is 17
OP-Act, Executing "unoconv -o /home/converter/cd525262d5de/187def1c07eb/sysbench_comparison.xlsx -f xlsx /var/www/html/HRProprietary/HRConvert2/DATA/cd525262d5de/187def1c07eb/sysbench_comparison.ods" on December 2, 2019, 10:29 am.
root@5db570c9d5c5:/var/www/html/HRProprietary/HRConvert2/Logs# unoconv -o /home/converter/cd525262d5de/187def1c07eb/sysbench_comparison.xlsx -f xlsx /var/www/html/HRProprietary/HRConvert2/DATA/cd525262d5de/187def1c07eb/sysbench_comparison.ods
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
root@5db570c9d5c5:/var/www/html/HRProprietary/HRConvert2/Logs# 
root@5db570c9d5c5:/var/www/html/HRProprietary/HRConvert2/Logs# 
```

**Comment by changchichung** [comment]
after some digging , I found that command in log 
```
OP-Act, Executing "unoconv -o /home/converter/cd525262d5de/6781e2ad27c0/0.xlsx -f xlsx /var/www/html/HRProprietary/HRConvert2/DATA/cd525262d5de/6781e2ad27c0/0.ods"
```
did not actually do the convert , I can manually run the command in console and get the file converted in /home/converter , but dunno why , that command just did not run via web .

**Comment by changchichung** [comment]
and when run the command with www-data users , there is an error .
```
www-data@3a834c8ab340:~/html/HRProprietary/HRConvert2$ unoconv -o /home/converter/cd525262d5de/1d5ea2baa919/0.xlsx -f xlsx /var/www/html/HRProprietary/HRConvert2/DATA/cd525262d5de/1d5ea2baa919/0.ods
Error: Unable to connect or start own listener. Aborting.
www-data@3a834c8ab340:~/html/HRProprietary/HRConvert2$ 
```

**Comment by changchichung** [comment]
OK then , now I found how to solve this issue.

www-data does not have permission to write /var/www , but the command will create /var/www/.cache/dconf and /var/www/.config/libreoffice 
login docker with root , and chmod -R www-data:www-data /var/www , then restart docker , and the convertation can be done now.
or modify Dockerfile , add chmod into it , and rebuild.

**Comment by zelon88** [comment]
Sorry it took me so long to reply to this. I remember looking at it a while ago and seeing that you got it fixed but I never responded. I apologize both for that and the fact that you had issues with HRConvert2. I'm glad you got it sorted. Permissions are the "Achilles heel" of most issues that I have with web applications these days.

Also, because you took the time to report an issue and the solution to it, and in accordance with the [HonestRepair Alternative Licensing Policy](https://www.honestrepair.net/index.php/alternative-licensing/) you are granted a [BSD 3-Clause License](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)) for HRConvert2 for life. Thanks for contributing to HonestRepair open-source software!

**Comment by alex-sandro92** [comment]
> OK then , now I found how to solve this issue.
> 
> www-data does not have permission to write /var/www , but the command will create /var/www/.cache/dconf and /var/www/.config/libreoffice login docker with root , and chmod -R www-data:www-data /var/www , then restart docker , and the convertation can be done now. or modify Dockerfile , add chmod into it , and rebuild.

I had a similar issue, but solved after giving read and write permissions to everyone on the "ConvertLoc" folder. The owner of that folder was already www-data but the converter didn't worked...
