### ISSUE TITLE
Support for subtitle conversions

### ISSUE THREAD

**Issue by Mupu** [zelon88/HRConvert2#32]
Hi, I wanted to suggest adding support for subtitle conversions. 
Basically what this here does: https://gotranscript.com/subtitle-converter

**Comment by zelon88** [comment]
I think we can probably get that done.

**Comment by zelon88** [comment]
Closing, as this was added in v3.1.9.1.

Additionally, in v3.3.1 you can control what types of subtitles HRConvert2 witll _ATTEMPT_ to convert via config.php.

**Comment by zelon88** [comment]
Forgot to click close.
