### ISSUE TITLE
.avi file not shown after successful upload

### ISSUE THREAD

**Issue by ctf-nc** [zelon88/HRConvert2#38]
Hi! This is a very nice project. I have been looking for more self hosting services for my homelab lately and this is awesome!

Could you help me with this issue? I was trying to convert a .avi video file to mp4. It successfully uploaded to the server (at least thats what i saw with a tick on the middle of the file after uploading.) However, after clicking continue, it said I have uploaded 0 valid files to HRConvert2. Below are the log output:

OP-Act, April 17, 2023, 12:24 pm: Logfile created using method 1.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Verified inbound connection.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Verified globals.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Verified required directories.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Cleaned temporary location.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Cleaned convert location.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Could not verify tokens!
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Verified color scheme.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Verified language.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/72e43169b3e3: Displaying the GUI.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Verified inbound connection.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Verified globals.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Created a directory at /data/HRConvert2/data/4d5d46f296a0/de58a3753093/.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Created a directory at /var/www/html/HRProprietary/HRConvert2/DATA/4d5d46f296a0/de58a3753093/.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Verified required directories.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Cleaned temporary location.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Cleaned convert location.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Verified tokens.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Verified color scheme.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Verified language.
Op-Act, April 17, 2023, 12:24 pm, 4d5d46f296a0/de58a3753093: Displaying the GUI.

Thanks again for this amazing project! Please tell me what i can help to troubleshoot the problems!

**Comment by LypticZ** [comment]
same shit with .mp4

**Comment by rworkm** [comment]
I'm having the same issue with .mp4 files.  Upload then click continue -> 0 valid files.

**Comment by reyist** [comment]
confirm, run in docker on NAS - 0 valid files with .mp4 files

**Comment by zelon88** [comment]
This sounds to be permissions related.
Can I ask the install method? 

Docker or bare-metal?

**Comment by zelon88** [comment]
- Can I ask who is running Docker and who is running bare-metal?
- Also Can I ask what happens if you follow the following instructions from the official installation instructions?






10. Adjust the directory in the following command to reflect the selected '$ConvertLoc' then run 'sudo chmod -R 0755 /Path/To/ConvertLoc'
11. Adjust the directory in the following command to reflect the selected '$ConvertLoc' then run 'sudo chown -R www-data /Path/To/ConvertLoc'
12. Adjust the directory in the following command to reflect the selected '$ConvertLoc' then run 'sudo chgrp -R www-data /Path/To/ConvertLoc'
