### ISSUE TITLE
Docker package for NAS 

### ISSUE THREAD

**Issue by NeilJared** [zelon88/HRConvert2#40]
Hi there! I would like to install it on a Synology NAS to use as file conversion tool, but I think it is not possible due to some software used.
On a similar idea is now working Stirling PDF; it does the job for pdf files, but would like to know whether HRConvert2 may be packaged in a near future as a big Docker package containing all stuff needed, or not. I have no programming skills to do so...
Cheers

**Comment by zelon88** [comment]
Hello! Thanks for your interest in HRConvert2. Sorry for the late reply.

If you can open a root terminal on the NAS, and have access to a package store, you can try to follow the installation instructions contained in the Documentation folder and see if it will install. If you can't get some of the dependencies to work, simply disable that conversion type in config.php to avoid the associated errors.

Also, there is a Docker repo maintained by Github user @dwaaan

https://github.com/dwaaan/HRConvert2-Docker
