### ISSUE TITLE
Error Timezone

### ISSUE THREAD

**Issue by JefPresotto** [zelon88/HRConvert2#44]
Após seguir o passo-a-passo (Toda a configuração de instalação ocorreu corretamente.) e abrir a pagina do conversor, é apresentado o seguinte erro:
ERROR!!! HRConvert2-4: Could not verify timezone!

Alguma idéia de como corrigir o problema?

Obrigado!

**Comment by JefPresotto** [comment]
Resolvido:

1 - Abra o arquivo php.ini
2 - Procure a linha ;date.timezone - No meu arquivo é a linha 978.
3 - remova o ponto-e-virgula e deixe da seguinte forma:
date.timezone = UTC
4 - salve o arquivo e feche.
5 - reinicie o apache:  service apache2 restart ou systemctl restart apache2
6 - abra a pagina inicial:  http://127.0.0.1/HRProprietary/HRConvert2/convertCore.php

**Comment by zelon88** [comment]
Thank you!
