### ISSUE TITLE
Access by API rest?

### ISSUE THREAD

**Issue by xorgxx** [zelon88/HRConvert2#47]
Hi it loop very attractive !!! but i have question | is there API rest access provide ? or it's in planning ...

Thank

**Comment by zelon88** [comment]
Hello, and thanks for your interest in HRConvert2. Sorry for the late reply.

There is another discussion that is very similar taking place at.....
https://github.com/zelon88/HRConvert2/issues/35

Also, the following information regarding the official API is from the official documentation.



    The following is a list of supported GET inputs & their supported values;
    noGui - 1
    language - String

    The following is a list of supported POST inputs & their supported values;
    Token1 - String
    Token2 - String
    height - Integer
    width - Integer
    rotate - Integer
    bitrate - Integer
    method - 0 or 1
    archive - 1
    extension - String
    filesToArchive - String or Array of Strings
    archExtension - String
    userfilename - String
    userconvertfilename - String
    pdfworkSelected - String or Array of Strings
    convertSelected - String or Array of Strings
    pdfextension - String
    userpdfconvertfilename - String
    scanallbutton - 1
    scantype - String (clamav or scancore or all)
    clamscanbutton - 1
    scancorebutton - 1
    filestoscan - String or Array of Strings
    clamScanButton - 1
    scancorebutton - 1
    scanallbutton - 1

**Comment by zelon88** [comment]
Closing.
