### ISSUE TITLE
The specified Data Storage Directory does not exist 

### ISSUE THREAD

**Issue by weir1** [zelon88/HRConvert2#48]
did all steps
but at the end
http://ip/HRProprietary/HRConvert2/convertCore.php
shows this
ERROR!!! January 9, 2024, 11:52 pm HRConvert2-1000: The specified Data Storage Directory does not exist at /pool_name/hrconvert/!

i tried docker first where everything worked except main conversion,, was getting empty file so tryied long installation process but failed too

**Comment by JFPCreations** [comment]
Same thing for me.

**Comment by JFPCreations** [comment]
This from the documentation correct my problem on the docker version. 
10. Adjust the directory in the following command to reflect the selected  '$ConvertLoc' then run  'sudo chmod -R 0755 /Path/To/ConvertLoc'
11. Adjust the directory in the following command to reflect the selected  '$ConvertLoc' then run  'sudo chown -R www-data /Path/To/ConvertLoc'
12. Adjust the directory in the following command to reflect the selected  '$ConvertLoc' then run  'sudo chgrp -R www-data /Path/To/ConvertLoc'

**Comment by zelon88** [comment]
Thank you @JFPCreations!
