### ISSUE TITLE
PHP Undefined variable

### ISSUE THREAD

**Issue by xsolinsx** [zelon88/HRConvert2#6]
Hello, I installed your software on my home server running apache2, I have problems converting pdf files into something else and videos into something else.
I get a white page "404 Not found, The requested URL was not found on this server."
Here I report the apache2 log of the subdomain to which hrconvert2 is connected
`[Sun May 10 00:48:32.782520 2020] [php7:notice] [pid 2795] [client MY_IP:49755] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59
[Sun May 10 00:48:32.841107 2020] [php7:notice] [pid 2795] [client MY_IP:49755] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/convertCore.php/
[Sun May 10 00:48:32.851332 2020] [php7:notice] [pid 2795] [client MY_IP:49755] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/convertCore.php/
[Sun May 10 00:48:32.859778 2020] [php7:notice] [pid 2788] [client MY_IP:49757] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/convertCore.php/
[Sun May 10 00:48:32.864942 2020] [php7:notice] [pid 2791] [client MY_IP:49758] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/convertCore.php/
[Sun May 10 00:48:32.905659 2020] [php7:notice] [pid 2795] [client MY_IP:49755] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59
[Sun May 10 00:49:17.739395 2020] [php7:error] [pid 2835] [client MY_IP:49769] script '/var/www/html/convertCore.php' not found or unable to stat
[Sun May 10 00:49:20.985209 2020] [php7:notice] [pid 2838] [client MY_IP:49772] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/
[Sun May 10 00:49:28.749973 2020] [php7:notice] [pid 2833] [client MY_IP:49776] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php
[Sun May 10 00:49:33.397059 2020] [php7:notice] [pid 2833] [client MY_IP:49776] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php
[Sun May 10 00:49:34.595430 2020] [php7:notice] [pid 2833] [client MY_IP:49776] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php
[Sun May 10 00:49:42.247098 2020] [php7:notice] [pid 2838] [client MY_IP:49780] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:42.249000 2020] [php7:notice] [pid 2838] [client MY_IP:49780] PHP Notice:  Undefined variable: UserID in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 374, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:42.249307 2020] [php7:warn] [pid 2838] [client MY_IP:49780] PHP Warning:  copy(/home/erics/HRConvert2_conversion/d85936abc361/75c314050cb1/DisOrdine__Regresso_on_Instagram_ldquoKaffeee_disordinati_\xf0\x9f\x91\xbd_EMBLEMA_Seguiteci_su_disordineeregresso____riservardquo.mp4): failed to open stream: No such file or directory in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 381, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:42.402671 2020] [php7:notice] [pid 2838] [client MY_IP:49780] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:55.044828 2020] [php7:notice] [pid 2834] [client MY_IP:49782] PHP Notice:  Undefined index: method in /var/www/html/HRProprietary/HRConvert2/sanitizeCore.php on line 150, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:55.045312 2020] [php7:notice] [pid 2834] [client MY_IP:49782] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:55.046685 2020] [php7:notice] [pid 2834] [client MY_IP:49782] PHP Notice:  Undefined variable: UserID in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 622, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:56.410442 2020] [php7:notice] [pid 2834] [client MY_IP:49782] PHP Notice:  Undefined variable: multiple in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 709, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1
[Sun May 10 00:49:57.837953 2020] [php7:notice] [pid 2834] [client MY_IP:49782] PHP Notice:  Undefined variable: URLEcho in /var/www/html/HRProprietary/HRConvert2/convertCore.php on line 59, referer: https://MY_DOMAIN:MY_PORT/HRProprietary/HRConvert2/convertCore.php?showFiles=1`

**Comment by zelon88** [comment]
Fixed in recent commits. Sorry for the delayed response!
