### ISSUE TITLE
Can't archive using rar at Raspberry Pi 4

### ISSUE THREAD

**Issue by bit-man** [zelon88/HRConvert2#63]
Only available Docker image is for linux/amd64 then build image for linux/arm64 and failed with

> E: Package 'rar' has no installation candidate

**Comment by bit-man** [comment]
The basic problem is that `rar` runs only in x86 architecture. One way to solve it is to run it using an x86 emulator and download the `rar` program from rarlabs

Already solved it at my [cloned HRConvert2-Docker](https://gitlab.com/the-automation-club/hrconvert2-docker). Take a look at [the complete log](https://gitlab.com/the-automation-club/hrconvert2-docker/-/issues/1)

**Comment by bit-man** [comment]
A pull request is on its way to solve it

**Comment by zelon88** [comment]
Thanks! Just merged. Gonna give it a shot in a little bit.

**Comment by zelon88** [comment]
Gonna close this one. Thanks again!

**Comment by bit-man** [comment]
@zelon88 sadly part of Dockerfile fixing this issue was reverted at commit https://github.com/zelon88/HRConvert2/commit/28a1cd1d3cf09d6ed41eddc65fc78e7bc3283aa7

**Comment by zelon88** [comment]
Re-fixed in 7cc41259ba9aa989a067f5852aa170173ae15cd7.

Sorry!
