### ISSUE TITLE
Cannot convert if spaces in the name

### ISSUE THREAD

**Issue by TheCableGuy99** [zelon88/HRConvert2#70]
Hi,

I just installed this for the first time and tried to convert a .png with a space in the name and it just gave an error saying it couldn't download it.

I changed the same file name to test.png and it works everytime with all formats. So clearly an issue with filenames containing spaces.

I can live with it as it's no big issue but thought i'd raise it incase you wanted to resolve it?

Thanks.

**Comment by zelon88** [comment]
Enjoy! 

This application comes with a detailed, comprehensive list of all error messages it produces in a file called "[ERROR_DESCRIPTIONS.txt](https://github.com/zelon88/HRConvert2/blob/master/Documentation/ERROR_DESCRIPTIONS.txt)" located in a folder called "Documentation". This folder is located right next to another folder that you may find useful called "Logs". 

I went to great lengths to give users like yourself the tools to troubleshoot these issues. It's kind of flattering that you still bumrush me instead with no logs or other actionable information to work with.

I built this for free, and I assure you it is still relevant. I've built this application in my spare time for the past 8 years... for free. I've written a about a quarter of a million lines of code in this and other repositories that you can download... for free. Sometimes I don't feel like working on this stuff for free, so I don't. If something is super important and you've done some due diligence you can always send me an email or a DM in the future and there is a good chance I'll respond.

Anyway I'm pretty sure this is an environmental thing. Whitespace in the filename of image conversions hasn't been an issue for many years.  There is well established code for handling such an event. Please check your logs, then check the docs, then create an issue.

Perhaps you have files with other empty characters or something. See [this link](https://emptycharacter.com/) for more information. It would be interesting to know for sure, but you didn't supply any log files. Log files which would have contained the exact filename, which would have been pretty easy to spot.

I just tested this in v3.3.7 and it works fine. The space is replaced with an underscore character.

**Comment by TheCableGuy99** [comment]
lol you got issues fellar hahaha
