### ISSUE TITLE
 Could not verify globals!

### ISSUE THREAD

**Issue by bit-man** [zelon88/HRConvert2#71]
According to [error descriptions](https://github.com/zelon88/HRConvert2/blob/460cbba211973010fa1257fe9742ee16d83183e6/Documentation/ERROR_DESCRIPTIONS.txt#L307) this happens when ` The version information contained in the versionInfo.php file does not match the version information contained in the convertCore.php file`

Happens that one of the says version 3.3.4 and the other one 3.3.5

**Comment by techdash** [comment]
Hi. Change the verion information in versionInfo.php file to 3.3.5 and then it shall work! The file is inside /Resources folder.

**Comment by bit-man** [comment]
Thanks for the _tip_ but yesterday prepared and tested a fix. Will do a pull request today

**Comment by techdash** [comment]
I need to ask as I am unable to install this converter. I am having NGINX server. Is that compatible with?

**Comment by zelon88** [comment]
Thanks!

I'm gearing up to put some time into the project. It's really hard to fit everything in but I haven't forgotten about what we have to accomplish here! I appreciate all your help.

@techdash I've never tried but I'm interesting in helping you troubleshoot the issue. For the sake of traceability and searchability, can I please ask you to open this as a separate issue and submit your Nginx error messages and log files over there?
